name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker Login
      run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag toky03/chiffrierung:0.0.${{ github.run_number }}
    - name: Push the Docker image
      run: docker push toky03/chiffrierung:0.0.${{ github.run_number }}